# This is a basic workflow to help you get started with Actions

name: Deploy to Salesforce Pipeline

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    #- uses: actions/checkout@v2

    # Setup Node
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    
    # Install SFDX CLI
    - name: Install SFDX CLI
      #run: npm install sfdx-cli --global
      #run: npm install -g sfdx-cli@latest-rc
      run: npm install @salesforce/cli --global
    
    # install SFDX-Git-Delta plugin - https://github.com/scolladon/sfdx-git-delta
    - name: 'Installing sfdx git delta'
      run: | 
            echo y | sfdx plugins:install sfdx-git-delta
            sfdx plugins 
            
    # Checkout the source code
    - name: 'Checkout source code'
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    # Authorize SF Org
    - name: Authorize SF Org
      env:
        CLIENT_ID: ${{ secrets.SALESFORCEPRODCLIENTID }}
      run: sfdx force:auth:jwt:grant --clientid 3MVG97quAmFZJfVzX9hl6Y_TDSbjsulFprCR3Pcao3UaucO8cn4bTCxZoD5XSl3wDRXq1bMs2IUDxoTEyZJfk --jwtkeyfile server.key --username arvindsing@gmail.com --instanceurl https://login.salesforce.com -a prod

    # Convert to Deploy Source
    - name: Convert to Deploy Source
      run: sfdx force:source:convert -r ./force-app -d ./toDeploy
    
    # Run Validation of Deploy Source
    
    # Deploy 
    - name : Deploy to SF Org
      #run: sfdx force:mdapi:deploy -l NoTestRun -d ./toDeploy -u prod -w 10
      run: sfdx force:mdapi:deploy -l NoTestRun -d ./toDeploy --ignorewarnings -u prod -w 100
